/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const IssueType = IDL.Variant({
  'inspection' : IDL.Null,
  'emergency' : IDL.Null,
  'quote' : IDL.Null,
});
export const FormEntry = IDL.Record({
  'issueType' : IssueType,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(FormEntry)], ['query']),
  'getSortedByIssueType' : IDL.Func([], [IDL.Vec(FormEntry)], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IssueType],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const IssueType = IDL.Variant({
    'inspection' : IDL.Null,
    'emergency' : IDL.Null,
    'quote' : IDL.Null,
  });
  const FormEntry = IDL.Record({
    'issueType' : IssueType,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(FormEntry)], ['query']),
    'getSortedByIssueType' : IDL.Func([], [IDL.Vec(FormEntry)], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IssueType],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };